import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  en: {
    // --------------------------------------------------------
    // Validation labels
    // --------------------------------------------------------
    requiredValidationMessage: "{0} can't be empty",
    emailValidationMessage: "'{0}' is not a valid email address",
    minLengthValidationMessage: "{0} can't be less than {1}",
    maxLengthValidationMessage: "{0} can't be more than {1}",
    rangeValidationMessage: '{0} should be between {1} and {2}',
    truthyValidationMessage: '{0} has to be truthy',

    // --------------------------------------------------------
    // API labels
    // --------------------------------------------------------

    timeoutMessageTitle: 'Something went wrong',
    timeoutMessageBody: 'Please try again in a few minutes',
    apiErrorGenericMessageTitle: 'Something went wrong',
    apiErrorGenericMessageBody: 'Please try again in a few minutes',
    networkRequestFailed: 'Something went wrong',
    genericErrorTitle: 'Something went wrong',
    genericErrorBody: 'Please try again in a short while.',

    // --------------------------------------------------------
    // Distance labels
    // --------------------------------------------------------

    kilometresLabel: 'km',
    metresLabel: 'm',

    // --------------------------------------------------------
    // Time labels
    // --------------------------------------------------------
    todayLabel: 'Today',
    tomorrowLabel: 'Tomorrow',
    minutesLabel: 'mins',

    // --------------------------------------------------------
    // Utilities
    // --------------------------------------------------------
    updateMessage: 'Please Click Here to Update App',
    noConnectionTitle: 'Trying to connect...',
    startupErrorTitle: 'Oh Snap!',
    startupErrorBody: 'Something went wrong.',
    startupErrorButtonTitle: 'Reload app',
    updateAvailableTitle: 'Uh uh!',
    updateAvailableBody: 'An important update is required to continue.',
    updateAvailableButtonTitle: 'Update to latest version',
    imagePickerErrorMessage: 'Something went wrong. Please try again.',
    maxFileSizeExceededMessage: 'Oops. That file is too large to be uploaded',
    passcodenotmatch: "Passcode don't match",
    correctpasscode: 'Enter correct Passcode',
    appOutdated: 'App is outdated',
    appOutdatedMessage: 'Please update the app to continue.',
    athleteAccessDeniedTitle: 'Access Denied',
    athleteAccessDeniedDescription:
      "You don't have access to view this ID number. If you have any concerns, please contact your supervisor or email support@iracesafe.com",
    inAppTraining: 'In-App Training',
    inAppTrainingTurnOn: 'You enabled the in-app training',
    inAppTrainingTurnOff: 'You disabled the in-app training',
    close: 'Close',

    // --------------------------------------------------------
    // Form strings
    // --------------------------------------------------------
    upload: 'Upload',
    emailLabel: 'Email',
    idLabel: 'ENTER ID #',
    pulse: 'Pulse',
    bloodpressure: 'Blood Pressure',
    breathing: 'Breathing',
    temperature: 'Temperature',
    o2saturation: '02 Saturation',
    sodium: 'Sodium',
    glucose: 'Glucose',
    note: 'Note',
    medication: 'Medication',
    dose: 'Dose',
    route: 'Route',
    otherAddnotes: 'Other (Add Notes)',
    status: 'Status',
    timeEventResolved: 'Time Event Resolved *',
    tapToEdit: '* Tap to Edit',
    emailPlaceholder: 'e.g. jon@example.com',
    firstNameLabel: 'First name',
    athleteStatus: 'Athlete Status',
    firstNamePlaceholder: 'e.g. Jon',
    successStatus: 'SUCCESS',
    lastNameLabel: 'Last name',
    notes: 'Notes',
    lastNamePlaceholder: 'e.g. Doe',
    userNameLabel: 'Username',
    userNamePlaceholder: 'e.g. jondoe',
    phoneLabel: 'Phone number',
    careProvider: 'Care Provider',
    reportedBy: 'Reported by',
    hospital: 'Hospital',
    phonePlaceholder: '8122-09-1994',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    verificationCodeLabel: 'Verification code',
    recoveryCodeLabel:
      'Please enter your Passcode that will be used to unlock the app.',
    reEnterRecoveryCodeLabel: 'Re-enter your Passcode',
    otpInputPlaceholder: '•',
    forgotPasswordLabel: 'Forgot Password?',
    setPasscode: 'Set Passcode',
    enterPasscode: 'Enter Passcode',
    practicerace: 'Practice Race',
    pickanevent: 'Pick an Event',
    channels: 'Channels',
    enterid: 'ENTER ID',
    helpCenter: 'Help Center',
    goHelpCenter: 'Go to Help Center',
    tryAgain: 'Try again',
    checkRegion: 'Check Region',
    referenceCenter: 'Reference Center',
    referenceCenterV2: 'Reference Center V2',
    cantLogIn: "Can't Log In",
    dontHaveAccount: "Don't have an Account?",
    register: 'REGISTER',
    send: 'SEND',
    forgotPassword: 'Forgot Password',
    back: 'Back',
    ok: 'Ok',
    takecareofanewproblem: 'Record a New Problem',
    enterANewProblem: 'Enter a New Problem',
    selectAnExistingProblem: 'Add to an Existing Problem',
    finishNotes: 'Complete Notes (No new visit)',
    followup: 'Follow Up',
    done: 'Done',
    addnote: 'Add Note',
    addfreeforminput: 'Add freeform input here',
    confirm: 'Confirm',
    locationOff:
      'Kindly turn your gps on as without it, we use your assigned location for the medical data and if unassigned please reach out to command.',
    duplicateIdsFound: 'Duplicate IDs Found',
    searchListInfo:
      'More than one athlete has the same search ID, please select the correct one',
    spotInjury: 'SPOT - INJURY',
    spotIllness: 'SPOT - ILLNESS',
    idsearchedhasnoathlete: 'ID searched has no athlete',
    youcanmakeNMR: 'You can make a new medical record below',
    heatProtocol: 'Heat Protocol',
    save: 'Save',
    bodypartinjured: 'Body Part Injured',
    vitalsigns: 'Vital Signs',
    symptoms: 'Symptoms',
    physicalFindings: 'Physical Findings',
    opinion: 'Opinion',
    treatment: 'Treatment',
    dateOfBirth: 'Date Of Birth',
    notifications: 'Notifications',

    //-------------------------------------------------------
    //SPOT
    //--------------------------------------------------------
    providingCare: 'Providing Care',
    enterSpotorLab: 'Enter SPOT or LAB data',
    history: 'History',
    makeACall: 'Make a Call',
    noProblemRecorded: 'No Problem Recorded',
    takeaphoto: 'Take a photo',
    uploadFile: 'Upload file',
    viewAmrConsent: 'View Consent form',
    resolveEvent: 'Resolve Problem',
    addInjury: 'Add Injury',
    addIllness: 'Add Illness',
    minor: 'Minor',
    delayed: 'Delayed',
    immediate: 'Immediate',
    otherpleaseadd: 'Other (Please add)',
    cancel: 'Cancel',
    left: 'Left',
    right: 'Right',
    bilateral: 'Bilateral',

    // --------------------------------------------------------
    // Application strings
    // --------------------------------------------------------
    openRecordsCount: 'You have {0} Open Records to Close',
    youSelected: 'You Selected',
    adminDetected: 'Admin Detected',
    pleaseSelectData: 'Please select the data to save.',
    selectAction: 'What do you want to do next? Select an option or cancel',
    isanewvisit: 'Is this a new visit?',
    adminDetectedSub:
      'Hello, I see you are a super admin, please, choose the server you want to connect to. Remember that in order to change servers you need to logout and login again.',
    usa: 'USA',
    canada: 'Canada',
    germany: 'German',
    ireland: 'Ireland',
    logout: 'Logout',
    contacts: 'Contacts',
    yourResolvedRecords: 'Your Resolved Records',
    yourOfflineRecords: 'Your Offline Records',
    yourActiveRecords: 'Your Open Records',
    checkedInRecords: 'Checked-In Records',
    language: 'Language',
    pickEvent: 'Pick an Event',
    deleteAccount: 'Delete Account',
    home: 'Home',
    yes: 'Yes',
    no: 'No',
    eventAction: 'eventAction',
    eventDisposition: 'eventDisposition',
    minorAssisitance: 'minorAssisitance',
    checkin: 'checkin',
    checkout: 'checkout',
    forgotPasswordSub:
      "Enter your email address and we'll email instructions for accessing your account",
    biometricsPopupTitleAndroid: 'Confirm your biometrics to continue',
    biometricsPopupTitleIOS: 'Confirm your biometrics to continue',
    biometricsAuthenticationFailed: 'Biometrics authentication failed',
    appleSignInButtonTitle: 'Sign in with Apple',
    facebookSignInButtonTitle: 'Continue with Facebook',
    loginButtonTitle: 'Log in',
    signUpButtonTitle: 'Sign up',
    signUpModalTitle: 'Sign up',
    signUpModalSubtitle: 'Get started in a few simple steps!',
    facebookSignUpButtonTitle: 'Sign up with Facebook',
    googleSignUpButtonTitle: 'Sign up with Google',
    emailSignUpButtonTitle: 'Get started now',
    appleSignUpButtonTitle: 'Sign up with Apple',
    loginTitle: 'Welcome back!',
    loginSubtitle: 'Sign in with your email and password to continue.',
    signInButtonTitle: 'SIGN IN',
    enterManualRunnerInfo: 'Enter manual runner information',
    createMedicalRecord: 'Create Medical Record',
    confirmInfo: 'Confirm Information',
    searchAthleteMed: 'Search Athlete Medical Record',
    recordMinorAssistance: 'Record Minor Assistance',
    searchAthleteMedTrans: 'Search Athlete Medical Record',
    recordMinorAssistanceTrans: 'Record Minor Assistance',
    checkIn: 'Check In',
    checkOut: 'Check Out',
    altSignInTitle: 'or sign in with',
    signInTermsText: 'By continuing, you confirm that you agree with our',
    termsLinkTitle: 'terms and conditions',
    registerPretitle: 'STEP {0} OF {1}',
    registerTitle: 'Create an account.',
    signUpNextButtonTitle: 'Next',
    signUpFinishButtonTitle: 'Finish',
    authHelpButtonTitle: 'Help',
    profileSelectTitle: 'Choose your profile type.',
    profileSelectSubtitle:
      'Select your profile type to proceed to the next step.',
    verifyTitle: 'Verify your email',
    verifySubtitle: 'We sent your verification code to {0}.',
    resendCodeText: "Didn't get the code?",
    resendCodeTimerText: 'Resend in ',
    resendCodeButtonText: 'Tap to resend',
    verifyButtonTitle: 'Verify',
    servicesModalDefaultTitle: 'What services do you offer?',
    servicesModalButtonTitle: 'Select {0} {1}',
    onboardingCompleteTitle: 'Great job!',
    onboardingCompleteFacilityManagerButtonTitle: 'Create an estate',
    onboardingCompleteVendorButtonTitle: 'Add a bank account',
    incorrectEmailPassword: 'You have entered an incorrect email or password.',
    incorrectEmail: 'Incorrect Email or Email not registered',
    resetInstruction: 'Reset Instruction Sent',
    resetInstructionBody:
      'Kindly check email address and follow the instructions to reset password',
    onboardingCompleteAltButtonTitle: 'or continue to your dashboard',
    resetEmailTitle: 'Forgot password?',
    resetEmailSubtitle:
      'Enter the email you registered with and we’ll send you a recovery code.',
    resetCodeTitle: 'Verify your account.',
    resetCodeSubtitle: 'Please enter the 4 digit recovery code we sent to {0}.',
    resetPasswordTitle: 'Set a new password.',
    resetPasswordSubtitle:
      'Use a super memorable combination of letters, numbers and special characters.',
    resetContinueButton: 'Continue',
    resetFinishButton: 'Finish',
    networkIssue: 'Network Issue',
    connectToInternetToUploadData: 'Connect to the Internet to upload data',
    heyWait: 'Hey, wait!',
    whatDoYouWantToDo: 'What do you want to do?',
    scanQROrBarCode: 'Scan QR or Barcode',
    problemList: 'Problem List (Select to follow-up)',
    selectproblemList: 'Select all problems this relates to',
    closedRecords: 'Closed Records (select to view)',
    allergies: 'Allergies',
    currentMedications: 'Current Medications',
    illnessConditions: 'Illness Conditions',
    surgeries: 'Surgeries',
    musculoskeletalConditions: 'Musculoskeletal Conditions',
    athleteFiles: 'Athlete Files',

    selectOneOption: 'Select One Option',
    proceedToDelete: 'Proceed to delete account !',
    pickaLanguage: 'Pick a Language',
    resolveProblem: 'Resolve Problem',
    pickHospital: 'Pick Hospital',
    greatJob: 'Great job!',
    oops: 'Oops!',
    info: 'Info',
    successfullyResolvedProblem: 'You successfully resolved the problem',
    phoneCurrentLocation: "This Phone's Current Location",
    notNecessarilyLocationAthlete:
      '(Not necessarily the location of the athlete)',
    areYouSure: 'Are you sure?',
    aboutToDowngradeStatus:
      "You are about to downgrade the status, please confirm if you'd like to continue.",
    startSpecialProtocol: 'Start Special Protocol',
    openGallery: 'Open Gallery',
    camera: 'Camera',
    renameTopic: 'Rename Topic',
    messages: 'Messages',
    selectFile: 'Select file',
    renameTopicTitle: 'Rename Chat Topic',
    photoUploadedSuccess: 'Photo uploaded successfully',
    workingOfflineMode: 'Working in offline mode',
    alternativeFormsCommunication:
      'Please use alternative forms of communication until network coverage improves',
    selectProblem: 'Select Problem',
    closeEventWithoutOpinion: "You're Closing an Event Without an Opinion",
    existingDisposition: 'Existing Resolved Disposition',
    sureToCloseEventWithoutOpinion:
      'Are you sure you want to close this event without providing an opinion?',
    enterMedicationsGiven: 'Please, describe the medication given below',

    // --------------------------------------------------------
    // In App Training
    // --------------------------------------------------------
    iatModalTitle: 'In-App Training',
    iatModalSubtitle: 'Choose when to show In-App Training tips',
    iatShowNow: 'Turn On and Show Tips Now',
    iatShowLater: 'Turn On and Show Tips Later',
    iatShowNever: 'Turn Off Training',

    iatAddPerson: 'Add a Person if needed',
    iatShowsEvent: 'Shows Event',
    iatPickAnOption: 'Pick an Option',
    iatSelectSearchMethod: 'Select Search Method',
    iatOpenToReadRecord: 'Open to Read Record',
    iatOpenCameraOrUploadFile: 'Open camera or upload file',
    iatOpenToDocumentCare: 'Open to Document Care',
    iatStatus: 'Indicates / Changes Status',
    iatPersonalInformation: 'See Personal Information',
    iatAddNewProblem: 'Add New Problem',
    iatTouchToMakeACall: 'Touch to Make a Call',
    iatSelectAProblem:
      'Select a problem for follow up. Touch Eyeball to view note',
  },
  de: {
    // --------------------------------------------------------
    // API labels
    // --------------------------------------------------------

    timeoutMessageTitle: 'Something went wrong',
    timeoutMessageBody: 'Please try again in a few minutes',
    apiErrorGenericMessageTitle: 'Something went wrong',
    apiErrorGenericMessageBody: 'Please try again in a few minutes',
    networkRequestFailed: 'Something went wrong',
    genericErrorTitle: 'Something went wrong',
    genericErrorBody: 'Please try again in a short while.',

    // --------------------------------------------------------
    // Utilities
    // --------------------------------------------------------
    updateMessage: 'Bitte hier klicken, um die App zu aktualisieren',
    noConnectionTitle: 'Trying to connect...',
    startupErrorTitle: 'Oh Snap!',
    startupErrorBody: 'Something went wrong.',
    startupErrorButtonTitle: 'Reload app',
    updateAvailableTitle: 'Uh uh!',
    updateAvailableBody: 'An important update is required to continue.',
    updateAvailableButtonTitle: 'Update to latest version',
    imagePickerErrorMessage: 'Something went wrong. Please try again.',
    maxFileSizeExceededMessage: 'Oops. That file is too large to be uploaded',
    passcodenotmatch: "Passcode don't match",
    correctpasscode: 'Enter correct Passcode',
    appOutdated: 'App ist veraltet',
    appOutdatedMessage: 'Bitte aktualisieren Sie die App, um fortzufahren.',
    athleteAccessDeniedTitle: 'Zugriff abgelehnt',
    athleteAccessDeniedDescription:
      'Sie haben keinen Zugriff, um diese ID-Nummer anzuzeigen. Wenn Sie Bedenken haben, wenden Sie sich bitte an Ihren Vorgesetzten oder senden Sie eine E-Mail an support@iracesafe.com',
    inAppTraining: 'In-App-Schulung',
    inAppTrainingTurnOn: 'Sie haben das In-App-Training aktiviert',
    inAppTrainingTurnOff: 'Sie haben das In-App-Training deaktiviert',
    close: 'Schließen',

    // --------------------------------------------------------
    // Form strings
    // --------------------------------------------------------
    viewAmrConsent: 'Einwilligungsformular anzeigen',
    openRecordsCount: 'You have {0} Open Records to Close',
    upload: 'Upload',
    emailLabel: 'Email',
    idLabel: 'ENTER ID #',
    pulse: 'Impuls',
    bloodpressure: 'Blutdruck',
    breathing: 'Atmung',
    temperature: 'Temperatur',
    o2saturation: '02 Sättigung',
    sodium: 'Natrium',
    glucose: 'Glucose',
    note: 'Notiz',
    medication: 'Medikament',
    dose: 'Dosis',
    route: 'Route',
    otherAddnotes: 'Sonstiges (Notizen hinzufügen)',
    status: 'Status',
    timeEventResolved: 'Zeitereignis aufgelöst *',
    tapToEdit: '* Tippen Sie zum Bearbeiten',
    emailPlaceholder: 'e.g. jon@example.com',
    firstNameLabel: 'First name',
    athleteStatus: 'Sportler-Status',
    firstNamePlaceholder: 'e.g. Jon',
    successStatus: 'SUCCESS',
    lastNameLabel: 'Last name',
    notes: 'Notes',
    lastNamePlaceholder: 'e.g. Doe',
    userNameLabel: 'Username',
    userNamePlaceholder: 'e.g. jondoe',
    phoneLabel: 'Phone number',
    careProvider: 'Pflegeanbieter',
    reportedBy: 'Berichtet von',
    hospital: 'Krankenhaus',
    phonePlaceholder: '8122-09-1994',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    verificationCodeLabel: 'Verification code',
    recoveryCodeLabel:
      'Bitte geben Sie Ihren Passcode ein, der zum Entsperren der App verwendet wird.',
    reEnterRecoveryCodeLabel: 'Re-enter your Passcode',
    otpInputPlaceholder: '•',
    forgotPasswordLabel: 'Forgot Password?',
    setPasscode: 'Passcode festlegen',
    enterPasscode: 'Passwort eingeben',
    practicerace: 'Übungsrennen',
    pickanevent: 'Wählen Sie ein Ereignis aus',
    enterid: 'ID EINGEBEN',
    helpCenter: 'Hilfezentrum',
    referenceCenter: 'Referenzzentrum',
    cantLogIn: "Can't Log In",
    dontHaveAccount: "Don't have an Account?",
    register: 'REGISTER',
    send: 'SEND',
    forgotPassword: 'Forgot Password',
    back: 'Zurück',
    ok: 'Ok',
    takecareofanewproblem: 'Um ein neues Problem kümmern',
    enterANewProblem: 'Geben Sie ein neues Problem ein',
    selectAnExistingProblem: 'Wählen Sie ein bestehendes Problem aus',
    followup: 'Nachverfolgen',
    done: 'Erledigt',
    addnote: 'Add Note',
    renameTopicTitle: 'Rename Chat Topic',
    addfreeforminput: 'Fügen Sie hier Freiformeingaben hinzu',
    confirm: 'Bestätigen',
    duplicateIdsFound: 'Doppelte IDs gefunden',
    searchListInfo:
      'Mehrere Athleten haben dieselbe Such-ID, bitte wählen Sie die richtige aus',
    spotInjury: 'SPOT - INJURY',
    spotIllness: 'SPOT - ILLNESS',
    idsearchedhasnoathlete: 'ID gesucht hat keinen Athleten',
    youcanmakeNMR: 'Unten können Sie eine neue Krankenakte erstellen',
    heatProtocol: 'Hitze Protocol',
    save: 'Speichern',
    bodypartinjured: 'Körperteil verletzt',
    vitalsigns: 'Vitalfunktionen',
    symptoms: 'Symptome',
    physicalFindings: 'Körperliche Befunde',
    opinion: 'Meinung',
    treatment: 'Behandlung',
    dateOfBirth: 'Geburtsdatum',
    notifications: 'Benachrichtigungen',

    //-------------------------------------------------------
    //SPOT
    //--------------------------------------------------------
    providingCare: 'Behandeln',
    enterSpotorLab: 'Geben Sie SPOT- oder LAB-Daten ein',
    history: 'Geschichte',
    makeACall: 'Einen Anruf tätigen',
    takeaphoto: 'Mach ein Foto',
    uploadFile: 'Datei hochladen',
    resolveEvent: 'Ein Problem lösen',
    addInjury: 'Verletzung hinzufügen',
    addIllness: 'Krankheit hinzufügen',
    minor: 'Minor',
    delayed: 'Delayed',
    immediate: 'Immediate',
    otherpleaseadd: 'Sonstiges (Bitte hinzufügen)',
    cancel: 'Zurück',
    left: 'Left',
    right: 'Right',
    bilateral: 'Bilateral',

    // --------------------------------------------------------
    // Application strings
    // --------------------------------------------------------
    goHelpCenter: 'Go to Help Center',
    tryAgain: 'Try again',
    checkRegion: 'Check Region',
    youSelected: 'You Selected',
    adminDetected: 'Admin Detected',
    pleaseSelectData: 'Bitte wählen Sie die zu speichernden Daten aus.',
    selectAction:
      'Was willst du als nächstes tun? Wählen Sie eine Option oder gehen Sie zurück',
    isanewvisit: 'Is this a new visit?',
    adminDetectedSub:
      'Hello, I see you are a super admin, please, choose the server you want to connect to. Remember that in order to change servers you need to logout and login again.',
    usa: 'USA',
    canada: 'Canada',
    germany: 'German',
    logout: 'Ausloggen',
    language: 'Sprache',
    contacts: 'Kontakte',
    yourResolvedRecords: 'Ihre aufgelösten Aufzeichnungen',
    yourOfflineRecords: 'Ihre Offline-Aufzeichnungen',
    yourActiveRecords: 'Ihre offenen Aufzeichnungen',
    checkedInRecords: 'Ihre eingecheckten Aufzeichnungen',
    pickEvent: 'Wählen Sie ein Ereignis aus',
    deleteAccount: 'Konto löschen',
    home: 'Heim',
    yes: 'Yes',
    no: 'No',
    eventAction: 'eventAction',
    eventDisposition: 'eventDisposition',
    minorAssisitance: 'minorAssisitance',
    checkin: 'checkin',
    checkout: 'checkout',
    forgotPasswordSub:
      'Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen per E-Mail Anweisungen für den Zugriff auf Ihr Konto',
    biometricsPopupTitleAndroid: 'Confirm your biometrics to continue',
    biometricsPopupTitleIOS: 'Confirm your biometrics to continue',
    biometricsAuthenticationFailed: 'Biometrics authentication failed',
    appleSignInButtonTitle: 'Sign in with Apple',
    facebookSignInButtonTitle: 'Continue with Facebook',
    loginButtonTitle: 'Log in',
    signUpButtonTitle: 'Sign up',
    signUpModalTitle: 'Sign up',
    signUpModalSubtitle: 'Get started in a few simple steps!',
    facebookSignUpButtonTitle: 'Sign up with Facebook',
    googleSignUpButtonTitle: 'Sign up with Google',
    emailSignUpButtonTitle: 'Get started now',
    appleSignUpButtonTitle: 'Sign up with Apple',
    loginTitle: 'Welcome back!',
    loginSubtitle: 'Sign in with your email and password to continue.',
    signInButtonTitle: 'SIGN IN',
    enterManualRunnerInfo: 'Geben Sie manuelle Läuferinformationen ein',
    createMedicalRecord: 'Erstellen Sie eine Krankenakte',
    confirmInfo: 'Informationen bestätigen',
    searchAthleteMed: 'Search Athlete Medical Record',
    recordMinorAssistance: 'Record Minor Assistance',
    searchAthleteMedTrans: 'Durchsuchen Sie die Krankenakte des Athleten',
    recordMinorAssistanceTrans: 'Notieren Sie kleinere Hilfeleistungen',
    checkIn: 'Check In',
    checkOut: 'Check Out',
    altSignInTitle: 'or sign in with',
    signInTermsText: 'By continuing, you confirm that you agree with our',
    termsLinkTitle: 'terms and conditions',
    registerPretitle: 'STEP {0} OF {1}',
    registerTitle: 'Create an account.',
    signUpNextButtonTitle: 'Next',
    signUpFinishButtonTitle: 'Finish',
    authHelpButtonTitle: 'Help',
    profileSelectTitle: 'Choose your profile type.',
    profileSelectSubtitle:
      'Select your profile type to proceed to the next step.',
    verifyTitle: 'Verify your email',
    verifySubtitle: 'We sent your verification code to {0}.',
    resendCodeText: "Didn't get the code?",
    resendCodeTimerText: 'Resend in ',
    resendCodeButtonText: 'Tap to resend',
    verifyButtonTitle: 'Verify',
    servicesModalDefaultTitle: 'What services do you offer?',
    servicesModalButtonTitle: 'Select {0} {1}',
    onboardingCompleteTitle: 'Great job!',
    incorrectEmailPassword: 'You have entered an incorrect email or password.',
    incorrectEmail: 'Incorrect Email or Email not registered',
    resetInstruction: 'Reset Instruction Sent',
    resetInstructionBody:
      'Kindly check email address and follow the instructions to reset password',
    onboardingCompleteAltButtonTitle: 'or continue to your dashboard',
    resetEmailTitle: 'Forgot password?',
    resetEmailSubtitle:
      'Enter the email you registered with and we’ll send you a recovery code.',
    resetCodeTitle: 'Verify your account.',
    resetCodeSubtitle: 'Please enter the 4 digit recovery code we sent to {0}.',
    resetPasswordTitle: 'Set a new password.',
    resetPasswordSubtitle:
      'Use a super memorable combination of letters, numbers and special characters.',
    resetContinueButton: 'Continue',
    resetFinishButton: 'Finish',
    networkIssue: 'Network Issue',
    connectToInternetToUploadData:
      'Stellen Sie eine Verbindung zum Internet her, um Daten hochzuladen',
    heyWait: 'Hey warte!',
    whatDoYouWantToDo: 'Was möchten Sie tun?',
    scanQROrBarCode: 'QR oder Barcode scannen',
    problemList: 'Problemliste',
    closedRecords: 'Geschlossene Aufzeichnungen (zum Anzeigen auswählen)',
    allergies: 'Allergien',
    currentMedications: 'Derzeitige Medikamente',
    illnessConditions: 'Krankheitsbedingungen',
    surgeries: 'Operationen',
    musculoskeletalConditions: 'Erkrankungen des Bewegungsapparates',
    athleteFiles: 'Athletendateien',

    enterMedicationsGiven:
      'Bitte beschreiben Sie die unten aufgeführten Medikamente',
    selectOneOption: 'Wählen Sie eine Option',
    proceedToDelete: 'Fahren Sie mit dem Löschen des Kontos fort !',
    pickaLanguage: 'Wählen Sie eine Sprache',
    resolveProblem: 'Ein Problem lösen',
    pickHospital: 'Wählen Sie Krankenhaus',
    greatJob: 'Gut gemacht!',
    oops: 'Hoppla!',
    successfullyResolvedProblem: 'Sie haben das Problem erfolgreich gelöst',
    phoneCurrentLocation: 'Der aktuelle Standort dieses Telefons',
    notNecessarilyLocationAthlete:
      '(Nicht unbedingt der Standort des Sportlers)',
    areYouSure: 'Bist du dir sicher?',
    aboutToDowngradeStatus:
      'Sie sind im Begriff, den Status herabzustufen. Bitte bestätigen Sie, ob Sie fortfahren möchten.',
    startSpecialProtocol: 'Spezielles Protokoll starten',
    openGallery: 'Galerie öffnen',
    camera: 'Kamera',
    selectFile: 'Datei aussuchen',
    photoUploadedSuccess: 'Foto erfolgreich hochgeladen',
    workingOfflineMode: 'Arbeiten im Offline-Modus',
    alternativeFormsCommunication:
      'Bitte nutzen Sie alternative Kommunikationsformen, bis sich die Netzabdeckung verbessert',
    selectProblem: 'Wählen Sie Problem',
    closeEventWithoutOpinion:
      'Sie schließen eine Veranstaltung ohne Stellungnahme ab',
    existingDisposition: 'Exisiting Disposition',
    sureToCloseEventWithoutOpinion:
      'Sind Sie sicher, dass Sie diese Veranstaltung schließen möchten, ohne eine Meinung abzugeben??',

    // --------------------------------------------------------
    // In App Training
    // --------------------------------------------------------
    iatModalTitle: 'In-App-Schulung',
    iatModalSubtitle:
      'Wählen Sie aus, wann In-App-Schulungstipps angezeigt werden sollen',
    iatShowNow: 'Jetzt einschalten und Tipps anzeigen',
    iatShowLater: 'Einschalten und Tipps später anzeigen',
    iatShowNever: 'Training ausschalten',

    iatAddPerson: 'Person hinzufügen, falls erforderlich',
    iatShowsEvent: 'Zeigt Veranstaltung',
    iatPickAnOption: 'Option auswählen',
    iatSelectSearchMethod: 'Suchmethode auswählen',
    iatOpenToReadRecord: 'Datensatz anzeigen',
    iatOpenCameraOrUploadFile: 'Kamera öffnen oder Datei hochladen',
    iatOpenToDocumentCare: 'Zur Dokumentenpflege öffnen',
    iatStatus: 'Zeigt den Status an bzw. ändert ihn',
    iatPersonalInformation: 'Persönliche Informationen anzeigen',
    iatAddNewProblem: 'Neues Problem hinzufügen',
    iatTouchToMakeACall: 'Berühren, um einen Anruf zu tätigen',
    iatSelectAProblem:
      'Wählen Sie ein Problem zur Nachverfolgung aus. Berühren Sie Augapfel, um die Notiz anzuzeigen',
  },
  es: {
    // --------------------------------------------------------
    // API labels
    // --------------------------------------------------------

    timeoutMessageTitle: 'Something went wrong',
    timeoutMessageBody: 'Please try again in a few minutes',
    apiErrorGenericMessageTitle: 'Something went wrong',
    apiErrorGenericMessageBody: 'Please try again in a few minutes',
    networkRequestFailed: 'Something went wrong',
    genericErrorTitle: 'Something went wrong',
    genericErrorBody: 'Please try again in a short while.',

    // --------------------------------------------------------
    // Utilities
    // --------------------------------------------------------
    updateMessage: 'Por favor, haga clic aquí para actualizar la aplicación',
    noConnectionTitle: 'Trying to connect...',
    startupErrorTitle: 'Oh Snap!',
    startupErrorBody: 'Something went wrong.',
    startupErrorButtonTitle: 'Recargar aplicación',
    updateAvailableTitle: 'Uh uh!',
    updateAvailableBody: 'An important update is required to continue.',
    updateAvailableButtonTitle: 'Update to latest version',
    imagePickerErrorMessage: 'Algo salió mal. Inténtalo de nuevo.',
    maxFileSizeExceededMessage:
      'Ups. Ese archivo es demasiado grande para cargarlo.',
    passcodenotmatch: "Passcode don't match",
    correctpasscode: 'Enter correct Passcode',
    appOutdated: 'App is outdated',
    appOutdatedMessage: 'Please update the app to continue.',
    athleteAccessDeniedTitle: 'Acceso denegado',
    athleteAccessDeniedDescription:
      'No tienes acceso para ver este número de identificación. Si tiene alguna inquietud, comuníquese con su supervisor o envíe un correo electrónico a support@iracesafe.com',
    inAppTraining: 'Capacitación en la aplicación',
    inAppTrainingTurnOn: 'Habilitó la capacitación en la aplicación.',
    inAppTrainingTurnOff: 'Has desactivado la formación en la aplicación.',
    close: 'Cerca',

    // --------------------------------------------------------
    // Form strings
    // --------------------------------------------------------
    viewAmrConsent: 'Ver formulario de consentimiento',
    openRecordsCount: 'Tienes {0} registros abiertos para cerrar',
    upload: 'Upload',
    emailLabel: 'Email',
    idLabel: 'ENTER ID #',
    pulse: 'Frecuencia Cardiaca-FC',
    bloodpressure: 'Presión arterial',
    breathing: 'Respiración',
    temperature: 'Temperatura',
    o2saturation: '02 Saturación',
    sodium: 'Sodio',
    glucose: 'Glucosa',
    note: 'Nota',
    medication: 'Medicamento',
    dose: 'Dosis',
    route: 'Ruta',
    otherAddnotes: 'Otro (Agregar notas)',
    status: 'Estado',
    timeEventResolved: 'Tiempo Evento Resuelto *',
    tapToEdit: '* Pulsa para editar',
    emailPlaceholder: 'e.g. jon@example.com',
    firstNameLabel: 'Nombre de pila',
    athleteStatus: 'Estado del atleta',
    firstNamePlaceholder: 'e.g. Jon',
    successStatus: 'SUCCESS',
    lastNameLabel: 'Apellido',
    notes: 'Notas',
    lastNamePlaceholder: 'e.g. Doe',
    userNameLabel: 'Username',
    userNamePlaceholder: 'e.g. jondoe',
    phoneLabel: 'Phone number',
    careProvider: 'Proveedor de atención',
    reportedBy: 'Reportado por',
    hospital: 'Krankenhaus',
    phonePlaceholder: '8122-09-1994',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    verificationCodeLabel: 'Verification code',
    recoveryCodeLabel:
      'Ingrese su contraseña que se utilizará para desbloquear la aplicación.',
    reEnterRecoveryCodeLabel: 'Re-enter your Passcode',
    otpInputPlaceholder: '•',
    forgotPasswordLabel: 'Forgot Password?',
    setPasscode: 'Código de acceso establecido',
    enterPasscode: 'Introduce un código de acceso',
    practicerace: 'Carrera de practica',
    pickanevent: 'Elige un evento',
    channels: 'Canales',
    enterid: 'INTRODUCIR ID',
    helpCenter: 'Centro de ayuda',
    goHelpCenter: 'Go to Help Center',
    tryAgain: 'Try again',
    checkRegion: 'Check Region',
    referenceCenter: 'Centro de Referencia',
    referenceCenterV2: 'Centro de Referencia V2',
    cantLogIn: "Can't Log In",
    dontHaveAccount: "Don't have an Account?",
    register: 'REGISTER',
    send: 'SEND',
    forgotPassword: 'Forgot Password',
    back: 'Atrás',
    ok: 'Ok',
    takecareofanewproblem: 'Registrar un nuevo problema',
    enterANewProblem: 'Introduzca un nuevo problema',
    selectAnExistingProblem: 'Agregar a un problema existente',
    followup: 'Hacer un seguimiento',
    done: 'Hecho',
    addnote: 'Añadir la nota',
    renameTopicTitle: 'Cambiar el nombre del tema de chat',
    addfreeforminput: 'Agregue entrada de forma libre aquí',
    confirm: 'Confirmar',
    duplicateIdsFound: 'ID duplicadas encontradas',
    searchListInfo:
      'Más de un atleta tiene el mismo ID de búsqueda, seleccione el correcto',
    spotInjury: 'Lesión Actual',
    spotIllness: 'Enfermedad Actual',
    idsearchedhasnoathlete: 'El ID buscado no tiene atleta',
    youcanmakeNMR: 'Puede hacer un nuevo registro médico a continuación',
    heatProtocol: 'Protocolo de calor',
    save: 'Guardar',
    bodypartinjured: 'Parte del cuerpo lesionada',
    vitalsigns: 'Signos vitales',
    symptoms: 'Síntomas',
    physicalFindings: 'Hallazgos físicos',
    opinion: 'Opinión',
    treatment: 'Tratamiento',
    dateOfBirth: 'Date Of Birth',
    notifications: 'Notificaciones',

    //-------------------------------------------------------
    //SPOT
    //--------------------------------------------------------
    providingCare: 'Proporcionar atención',
    enterSpotorLab: 'Ingrese datos SPOT o LAB',
    history: 'Historia',
    makeACall: 'Haz una llamada',
    noProblemRecorded: 'No Problem Recorded',
    takeaphoto: 'Toma una foto',
    uploadFile: 'Subir archivo',
    resolveEvent: 'Resuelve el problema',
    addInjury: 'Agregar lesión',
    addIllness: 'Agregar enfermedad',
    minor: 'Minor',
    delayed: 'Delayed',
    immediate: 'Immediate',
    otherpleaseadd: 'Otro (por favor agregue)',
    cancel: 'Cancelar',
    left: 'Left',
    right: 'Right',
    bilateral: 'Bilateral',

    // --------------------------------------------------------
    // Application strings
    // --------------------------------------------------------
    youSelected: 'Tu seleccionaste',
    adminDetected: 'Admin Detected',
    pleaseSelectData: 'Por favor seleccione los datos para guardar.',
    selectAction:
      '¿Qué desea hacer a continuación? Seleccione una opción o cancele',
    isanewvisit: '¿Es una visita nueva?',
    adminDetectedSub:
      'Hello, I see you are a super admin, please, choose the server you want to connect to. Remember that in order to change servers you need to logout and login again.',
    usa: 'USA',
    canada: 'Canada',
    germany: 'German',
    logout: 'Cerrar sesión',
    contacts: 'Contactos',
    yourResolvedRecords: 'Tus Registros Resueltos',
    yourOfflineRecords: 'Tus Registros Sin Conexión',
    yourActiveRecords: 'Tus Registros Activos',
    checkedInRecords: 'Tus Registros Registrados',
    language: 'Idioma',
    pickEvent: 'Seleccionar un Evento',
    deleteAccount: 'Eliminar Cuenta',
    home: 'Hogar',
    yes: 'Yes',
    no: 'No',
    eventAction: 'eventAction',
    eventDisposition: 'eventDisposition',
    minorAssisitance: 'minorAssisitance',
    checkin: 'checkin',
    checkout: 'checkout',
    forgotPasswordSub:
      'Ingrese su dirección de correo electrónico y le enviaremos instrucciones para acceder a su cuenta.',
    biometricsPopupTitleAndroid: 'Confirm your biometrics to continue',
    biometricsPopupTitleIOS: 'Confirm your biometrics to continue',
    biometricsAuthenticationFailed: 'Biometrics authentication failed',
    appleSignInButtonTitle: 'Sign in with Apple',
    facebookSignInButtonTitle: 'Continue with Facebook',
    loginButtonTitle: 'Log in',
    signUpButtonTitle: 'Sign up',
    signUpModalTitle: 'Sign up',
    signUpModalSubtitle: 'Get started in a few simple steps!',
    facebookSignUpButtonTitle: 'Sign up with Facebook',
    googleSignUpButtonTitle: 'Sign up with Google',
    emailSignUpButtonTitle: 'Get started now',
    appleSignUpButtonTitle: 'Sign up with Apple',
    loginTitle: 'Welcome back!',
    loginSubtitle: 'Sign in with your email and password to continue.',
    signInButtonTitle: 'SIGN IN',
    enterManualRunnerInfo: 'Ingresar información del corredor manualmente',
    createMedicalRecord: 'Crear Expediente Médico',
    confirmInfo: 'Confirmar Información',
    searchAthleteMed: 'Search Athlete Medical Record',
    recordMinorAssistance: 'Record Minor Assistance',
    searchAthleteMedTrans: 'Buscar Expediente Médico del Atleta',
    recordMinorAssistanceTrans: 'Registrar Asistencia Menor',
    checkIn: 'Check In',
    checkOut: 'Check Out',
    altSignInTitle: 'or sign in with',
    signInTermsText: 'By continuing, you confirm that you agree with our',
    termsLinkTitle: 'terms and conditions',
    registerPretitle: 'STEP {0} OF {1}',
    registerTitle: 'Create an account.',
    signUpNextButtonTitle: 'Next',
    signUpFinishButtonTitle: 'Finish',
    authHelpButtonTitle: 'Help',
    profileSelectTitle: 'Choose your profile type.',
    profileSelectSubtitle:
      'Select your profile type to proceed to the next step.',
    verifyTitle: 'Verify your email',
    verifySubtitle: 'We sent your verification code to {0}.',
    resendCodeText: "Didn't get the code?",
    resendCodeTimerText: 'Resend in ',
    resendCodeButtonText: 'Tap to resend',
    verifyButtonTitle: 'Verify',
    servicesModalDefaultTitle: 'What services do you offer?',
    servicesModalButtonTitle: 'Select {0} {1}',
    onboardingCompleteTitle: 'Great job!',
    incorrectEmailPassword: 'You have entered an incorrect email or password.',
    incorrectEmail: 'Incorrect Email or Email not registered',
    resetInstruction: 'Reset Instruction Sent',
    resetInstructionBody:
      'Kindly check email address and follow the instructions to reset password',
    onboardingCompleteAltButtonTitle: 'or continue to your dashboard',
    resetEmailTitle: 'Forgot password?',
    resetEmailSubtitle:
      'Enter the email you registered with and we’ll send you a recovery code.',
    resetCodeTitle: 'Verify your account.',
    resetCodeSubtitle: 'Please enter the 4 digit recovery code we sent to {0}.',
    resetPasswordTitle: 'Set a new password.',
    resetPasswordSubtitle:
      'Use a super memorable combination of letters, numbers and special characters.',
    resetContinueButton: 'Continue',
    resetFinishButton: 'Finish',
    networkIssue: 'Network Issue',
    connectToInternetToUploadData: 'Conéctese a Internet para subir datos',
    heyWait: '¡Hey espera!',
    whatDoYouWantToDo: '¿Qué te gustaría hacer?',
    scanQROrBarCode: 'Escanear QR o código de barras',
    problemList: 'Lista de problemas',
    closedRecords: 'Registros cerrados (seleccionar para ver)',
    allergies: 'Alergias',
    currentMedications: 'Medicamentos actuales',
    illnessConditions: 'Condiciones de enfermedad',
    surgeries: 'Cirugías',
    musculoskeletalConditions: 'Condiciones musculoesqueléticas',
    athleteFiles: 'Archivos de atletas',

    enterMedicationsGiven:
      'Por favor, describa los medicamentos listados abajo',
    selectOneOption: 'Seleccione una opción',
    proceedToDelete: '¡Proceda a eliminar la cuenta!',
    pickaLanguage: 'Elija un idioma',
    resolveProblem: 'Resolver un problema',
    pickHospital: 'Elegir hospital',
    greatJob: '¡Buen trabajo!',
    oops: '¡Ups!',
    successfullyResolvedProblem: 'Ha resuelto el problema con éxito',
    phoneCurrentLocation: 'La ubicación actual de este teléfono',
    notNecessarilyLocationAthlete:
      '(No necesariamente la ubicación del atleta)',
    areYouSure: '¿Estás seguro?',
    aboutToDowngradeStatus:
      'Está a punto de rebajar el estado. Por favor, confirme si desea continuar.',
    startSpecialProtocol: 'Iniciar protocolo especial',
    openGallery: 'Abrir galería',
    camera: 'Cámara',
    selectFile: 'Seleccionar archivo',
    photoUploadedSuccess: 'Foto subida con éxito',
    workingOfflineMode: 'Trabajando en modo sin conexión',
    alternativeFormsCommunication:
      'Por favor, utilice formas alternativas de comunicación hasta que mejore la cobertura de red',
    selectProblem: 'Seleccione problema',
    closeEventWithoutOpinion: 'Está cerrando un evento sin emitir una opinión',

    existingDisposition: 'Exisiting Disposition',
    sureToCloseEventWithoutOpinion:
      '¿Está seguro de que desea cerrar este evento sin emitir una opinión?',

    // --------------------------------------------------------
    // In App Training
    // --------------------------------------------------------
    iatAddPerson: 'Agregar persona, si es necesario',
    iatShowsEvent: 'Muestra evento',
    iatPickAnOption: 'Seleccionar una opción',
    iatSelectSearchMethod: 'Seleccionar método de búsqueda',
    iatOpenToReadRecord: 'Abrir para ver registro',
    iatOpenCameraOrUploadFile: 'Abrir cámara o subir archivo',
    iatOpenToDocumentCare: 'Abrir para cuidado documental',
    iatStatus: 'Muestra o cambia el estado',
    iatPersonalInformation: 'Mostrar información personal',
    iatAddNewProblem: 'Agregar nuevo problema',
    iatTouchToMakeACall: 'Tocar para realizar una llamada',
    iatSelectAProblem:
      'Seleccione un problema para seguimiento. Toque el icono de ojo para mostrar la nota',
  },
  fr: {
    // --------------------------------------------------------
    // API labels
    // --------------------------------------------------------

    timeoutMessageTitle: 'Something went wrong',
    timeoutMessageBody: 'Please try again in a few minutes',
    apiErrorGenericMessageTitle: 'Something went wrong',
    apiErrorGenericMessageBody: 'Please try again in a few minutes',
    networkRequestFailed: 'Something went wrong',
    genericErrorTitle: 'Something went wrong',
    genericErrorBody: 'Please try again in a short while.',

    // --------------------------------------------------------
    // Utilities
    // --------------------------------------------------------
    updateMessage: "Veuillez cliquer ici pour mettre à jour l'application",
    noConnectionTitle: 'Trying to connect...',
    startupErrorTitle: 'Oh Snap!',
    startupErrorBody: 'Something went wrong.',
    startupErrorButtonTitle: 'Reload app',
    updateAvailableTitle: 'Uh uh!',
    updateAvailableBody: 'An important update is required to continue.',
    updateAvailableButtonTitle: 'Update to latest version',
    imagePickerErrorMessage: 'Something went wrong. Please try again.',
    maxFileSizeExceededMessage: 'Oops. That file is too large to be uploaded',
    passcodenotmatch: "Passcode don't match",
    correctpasscode: 'Enter correct Passcode',
    appOutdated: 'App ist veraltet',
    appOutdatedMessage: 'Bitte aktualisieren Sie die App, um fortzufahren.',
    athleteAccessDeniedTitle: 'Zugriff abgelehnt',
    athleteAccessDeniedDescription:
      'Sie haben keinen Zugriff, um diese ID-Nummer anzuzeigen. Wenn Sie Bedenken haben, wenden Sie sich bitte an Ihren Vorgesetzten oder senden Sie eine E-Mail an support@iracesafe.com',
    inAppTraining: 'In-App-Schulung',
    inAppTrainingTurnOn: 'Sie haben das In-App-Training aktiviert',
    inAppTrainingTurnOff: 'Sie haben das In-App-Training deaktiviert',
    close: 'Schließen',

    // --------------------------------------------------------
    // Form strings
    // --------------------------------------------------------
    viewAmrConsent: 'Voir le formulaire de consentement',
    openRecordsCount: 'You have {0} Open Records to Close',
    upload: 'Upload',
    emailLabel: 'Email',
    idLabel: 'ENTER ID #',
    pulse: 'Impuls',
    bloodpressure: 'Blutdruck',
    breathing: 'Atmung',
    temperature: 'Temperatur',
    o2saturation: '02 Sättigung',
    sodium: 'Natrium',
    glucose: 'Glucose',
    note: 'Notiz',
    medication: 'Medikament',
    dose: 'Dosis',
    route: 'Route',
    otherAddnotes: 'Sonstiges (Notizen hinzufügen)',
    status: 'Status',
    timeEventResolved: 'Zeitereignis aufgelöst *',
    tapToEdit: '* Tippen Sie zum Bearbeiten',
    emailPlaceholder: 'e.g. jon@example.com',
    firstNameLabel: 'First name',
    athleteStatus: 'Sportler-Status',
    firstNamePlaceholder: 'e.g. Jon',
    successStatus: 'SUCCESS',
    lastNameLabel: 'Last name',
    notes: 'Notes',
    lastNamePlaceholder: 'e.g. Doe',
    userNameLabel: 'Username',
    userNamePlaceholder: 'e.g. jondoe',
    phoneLabel: 'Phone number',
    careProvider: 'Pflegeanbieter',
    reportedBy: 'Berichtet von',
    hospital: 'Krankenhaus',
    phonePlaceholder: '8122-09-1994',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    verificationCodeLabel: 'Verification code',
    recoveryCodeLabel:
      'Bitte geben Sie Ihren Passcode ein, der zum Entsperren der App verwendet wird.',
    reEnterRecoveryCodeLabel: 'Re-enter your Passcode',
    otpInputPlaceholder: '•',
    forgotPasswordLabel: 'Forgot Password?',
    setPasscode: 'Passcode festlegen',
    enterPasscode: 'Passwort eingeben',
    practicerace: 'Übungsrennen',
    pickanevent: 'Wählen Sie ein Ereignis aus',
    enterid: 'ID EINGEBEN',
    helpCenter: 'Hilfezentrum',
    referenceCenter: 'Referenzzentrum',
    cantLogIn: "Can't Log In",
    dontHaveAccount: "Don't have an Account?",
    register: 'REGISTER',
    send: 'SEND',
    forgotPassword: 'Forgot Password',
    back: 'Zurück',
    ok: 'Ok',
    takecareofanewproblem: 'Um ein neues Problem kümmern',
    enterANewProblem: 'Geben Sie ein neues Problem ein',
    selectAnExistingProblem: 'Wählen Sie ein bestehendes Problem aus',
    followup: 'Nachverfolgen',
    done: 'Erledigt',
    addnote: 'Add Note',
    renameTopicTitle: 'Rename Chat Topic',
    addfreeforminput: 'Fügen Sie hier Freiformeingaben hinzu',
    confirm: 'Bestätigen',
    duplicateIdsFound: 'Doppelte IDs gefunden',
    searchListInfo:
      'Mehrere Athleten haben dieselbe Such-ID, bitte wählen Sie die richtige aus',
    spotInjury: 'SPOT - INJURY',
    spotIllness: 'SPOT - ILLNESS',
    idsearchedhasnoathlete: 'ID gesucht hat keinen Athleten',
    youcanmakeNMR: 'Unten können Sie eine neue Krankenakte erstellen',
    heatProtocol: 'Hitze Protocol',
    save: 'Speichern',
    bodypartinjured: 'Körperteil verletzt',
    vitalsigns: 'Vitalfunktionen',
    symptoms: 'Symptome',
    physicalFindings: 'Körperliche Befunde',
    opinion: 'Meinung',
    treatment: 'Behandlung',
    dateOfBirth: 'Geburtsdatum',
    notifications: 'Benachrichtigungen',

    //-------------------------------------------------------
    //SPOT
    //--------------------------------------------------------
    providingCare: 'Behandeln',
    enterSpotorLab: 'Geben Sie SPOT- oder LAB-Daten ein',
    history: 'Geschichte',
    makeACall: 'Einen Anruf tätigen',
    takeaphoto: 'Mach ein Foto',
    uploadFile: 'Datei hochladen',
    resolveEvent: 'Ein Problem lösen',
    addInjury: 'Verletzung hinzufügen',
    addIllness: 'Krankheit hinzufügen',
    minor: 'Minor',
    delayed: 'Delayed',
    immediate: 'Immediate',
    otherpleaseadd: 'Sonstiges (Bitte hinzufügen)',
    cancel: 'Zurück',
    left: 'Left',
    right: 'Right',
    bilateral: 'Bilateral',

    // --------------------------------------------------------
    // Application strings
    // --------------------------------------------------------
    goHelpCenter: 'Go to Help Center',
    tryAgain: 'Try again',
    checkRegion: 'Check Region',
    youSelected: 'You Selected',
    adminDetected: 'Admin Detected',
    pleaseSelectData: 'Bitte wählen Sie die zu speichernden Daten aus.',
    selectAction:
      'Was willst du als nächstes tun? Wählen Sie eine Option oder gehen Sie zurück',
    isanewvisit: 'Is this a new visit?',
    adminDetectedSub:
      'Hello, I see you are a super admin, please, choose the server you want to connect to. Remember that in order to change servers you need to logout and login again.',
    usa: 'USA',
    canada: 'Canada',
    germany: 'German',
    logout: 'Ausloggen',
    language: 'Sprache',
    contacts: 'Kontakte',
    yourResolvedRecords: 'Ihre aufgelösten Aufzeichnungen',
    yourOfflineRecords: 'Ihre Offline-Aufzeichnungen',
    yourActiveRecords: 'Ihre offenen Aufzeichnungen',
    checkedInRecords: 'Ihre eingecheckten Aufzeichnungen',
    pickEvent: 'Wählen Sie ein Ereignis aus',
    deleteAccount: 'Konto löschen',
    home: 'Heim',
    yes: 'Yes',
    no: 'No',
    eventAction: 'eventAction',
    eventDisposition: 'eventDisposition',
    minorAssisitance: 'minorAssisitance',
    checkin: 'checkin',
    checkout: 'checkout',
    forgotPasswordSub:
      'Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen per E-Mail Anweisungen für den Zugriff auf Ihr Konto',
    biometricsPopupTitleAndroid: 'Confirm your biometrics to continue',
    biometricsPopupTitleIOS: 'Confirm your biometrics to continue',
    biometricsAuthenticationFailed: 'Biometrics authentication failed',
    appleSignInButtonTitle: 'Sign in with Apple',
    facebookSignInButtonTitle: 'Continue with Facebook',
    loginButtonTitle: 'Log in',
    signUpButtonTitle: 'Sign up',
    signUpModalTitle: 'Sign up',
    signUpModalSubtitle: 'Get started in a few simple steps!',
    facebookSignUpButtonTitle: 'Sign up with Facebook',
    googleSignUpButtonTitle: 'Sign up with Google',
    emailSignUpButtonTitle: 'Get started now',
    appleSignUpButtonTitle: 'Sign up with Apple',
    loginTitle: 'Welcome back!',
    loginSubtitle: 'Sign in with your email and password to continue.',
    signInButtonTitle: 'SIGN IN',
    enterManualRunnerInfo: 'Geben Sie manuelle Läuferinformationen ein',
    createMedicalRecord: 'Erstellen Sie eine Krankenakte',
    confirmInfo: 'Informationen bestätigen',
    searchAthleteMed: 'Search Athlete Medical Record',
    recordMinorAssistance: 'Record Minor Assistance',
    searchAthleteMedTrans: 'Durchsuchen Sie die Krankenakte des Athleten',
    recordMinorAssistanceTrans: 'Notieren Sie kleinere Hilfeleistungen',
    checkIn: 'Check In',
    checkOut: 'Check Out',
    altSignInTitle: 'or sign in with',
    signInTermsText: 'By continuing, you confirm that you agree with our',
    termsLinkTitle: 'terms and conditions',
    registerPretitle: 'STEP {0} OF {1}',
    registerTitle: 'Create an account.',
    signUpNextButtonTitle: 'Next',
    signUpFinishButtonTitle: 'Finish',
    authHelpButtonTitle: 'Help',
    profileSelectTitle: 'Choose your profile type.',
    profileSelectSubtitle:
      'Select your profile type to proceed to the next step.',
    verifyTitle: 'Verify your email',
    verifySubtitle: 'We sent your verification code to {0}.',
    resendCodeText: "Didn't get the code?",
    resendCodeTimerText: 'Resend in ',
    resendCodeButtonText: 'Tap to resend',
    verifyButtonTitle: 'Verify',
    servicesModalDefaultTitle: 'What services do you offer?',
    servicesModalButtonTitle: 'Select {0} {1}',
    onboardingCompleteTitle: 'Great job!',
    incorrectEmailPassword: 'You have entered an incorrect email or password.',
    incorrectEmail: 'Incorrect Email or Email not registered',
    resetInstruction: 'Reset Instruction Sent',
    resetInstructionBody:
      'Kindly check email address and follow the instructions to reset password',
    onboardingCompleteAltButtonTitle: 'or continue to your dashboard',
    resetEmailTitle: 'Forgot password?',
    resetEmailSubtitle:
      'Enter the email you registered with and we’ll send you a recovery code.',
    resetCodeTitle: 'Verify your account.',
    resetCodeSubtitle: 'Please enter the 4 digit recovery code we sent to {0}.',
    resetPasswordTitle: 'Set a new password.',
    resetPasswordSubtitle:
      'Use a super memorable combination of letters, numbers and special characters.',
    resetContinueButton: 'Continue',
    resetFinishButton: 'Finish',
    networkIssue: 'Network Issue',
    connectToInternetToUploadData:
      'Stellen Sie eine Verbindung zum Internet her, um Daten hochzuladen',
    heyWait: 'Hey warte!',
    whatDoYouWantToDo: 'Was möchten Sie tun?',
    scanQROrBarCode: 'QR oder Barcode scannen',
    problemList: 'Problemliste',
    closedRecords: 'Geschlossene Aufzeichnungen (zum Anzeigen auswählen)',
    allergies: 'Allergien',
    currentMedications: 'Derzeitige Medikamente',
    illnessConditions: 'Krankheitsbedingungen',
    surgeries: 'Operationen',
    musculoskeletalConditions: 'Erkrankungen des Bewegungsapparates',
    athleteFiles: 'Athletendateien',

    enterMedicationsGiven:
      'Bitte beschreiben Sie die unten aufgeführten Medikamente',
    selectOneOption: 'Wählen Sie eine Option',
    proceedToDelete: 'Fahren Sie mit dem Löschen des Kontos fort !',
    pickaLanguage: 'Wählen Sie eine Sprache',
    resolveProblem: 'Ein Problem lösen',
    pickHospital: 'Wählen Sie Krankenhaus',
    greatJob: 'Gut gemacht!',
    oops: 'Hoppla!',
    successfullyResolvedProblem: 'Sie haben das Problem erfolgreich gelöst',
    phoneCurrentLocation: 'Der aktuelle Standort dieses Telefons',
    notNecessarilyLocationAthlete:
      '(Nicht unbedingt der Standort des Sportlers)',
    areYouSure: 'Bist du dir sicher?',
    aboutToDowngradeStatus:
      'Sie sind im Begriff, den Status herabzustufen. Bitte bestätigen Sie, ob Sie fortfahren möchten.',
    startSpecialProtocol: 'Spezielles Protokoll starten',
    openGallery: 'Galerie öffnen',
    camera: 'Kamera',
    selectFile: 'Datei aussuchen',
    photoUploadedSuccess: 'Foto erfolgreich hochgeladen',
    workingOfflineMode: 'Arbeiten im Offline-Modus',
    alternativeFormsCommunication:
      'Bitte nutzen Sie alternative Kommunikationsformen, bis sich die Netzabdeckung verbessert',
    selectProblem: 'Wählen Sie Problem',
    closeEventWithoutOpinion:
      'Sie schließen eine Veranstaltung ohne Stellungnahme ab',
    existingDisposition: 'Exisiting Disposition',
    sureToCloseEventWithoutOpinion:
      'Sind Sie sicher, dass Sie diese Veranstaltung schließen möchten, ohne eine Meinung abzugeben??',

    // --------------------------------------------------------
    // In App Training
    // --------------------------------------------------------
    iatModalTitle: 'In-App-Schulung',
    iatModalSubtitle:
      'Wählen Sie aus, wann In-App-Schulungstipps angezeigt werden sollen',
    iatShowNow: 'Jetzt einschalten und Tipps anzeigen',
    iatShowLater: 'Einschalten und Tipps später anzeigen',
    iatShowNever: 'Training ausschalten',

    iatAddPerson: 'Person hinzufügen, falls erforderlich',
    iatShowsEvent: 'Zeigt Veranstaltung',
    iatPickAnOption: 'Option auswählen',
    iatSelectSearchMethod: 'Suchmethode auswählen',
    iatOpenToReadRecord: 'Datensatz anzeigen',
    iatOpenCameraOrUploadFile: 'Kamera öffnen oder Datei hochladen',
    iatOpenToDocumentCare: 'Zur Dokumentenpflege öffnen',
    iatStatus: 'Zeigt den Status an bzw. ändert ihn',
    iatPersonalInformation: 'Persönliche Informationen anzeigen',
    iatAddNewProblem: 'Neues Problem hinzufügen',
    iatTouchToMakeACall: 'Berühren, um einen Anruf zu tätigen',
    iatSelectAProblem:
      'Wählen Sie ein Problem zur Nachverfolgung aus. Berühren Sie Augapfel, um die Notiz anzuzeigen',
  },
  pt: {
    // --------------------------------------------------------
    // API labels
    // --------------------------------------------------------

    timeoutMessageTitle: 'Something went wrong',
    timeoutMessageBody: 'Please try again in a few minutes',
    apiErrorGenericMessageTitle: 'Something went wrong',
    apiErrorGenericMessageBody: 'Please try again in a few minutes',
    networkRequestFailed: 'Something went wrong',
    genericErrorTitle: 'Something went wrong',
    genericErrorBody: 'Please try again in a short while.',

    // --------------------------------------------------------
    // Utilities
    // --------------------------------------------------------
    updateMessage: 'Por favor, clique aqui para atualizar o aplicativo',
    noConnectionTitle: 'Trying to connect...',
    startupErrorTitle: 'Oh Snap!',
    startupErrorBody: 'Something went wrong.',
    startupErrorButtonTitle: 'Reload app',
    updateAvailableTitle: 'Uh uh!',
    updateAvailableBody: 'An important update is required to continue.',
    updateAvailableButtonTitle: 'Update to latest version',
    imagePickerErrorMessage: 'Something went wrong. Please try again.',
    maxFileSizeExceededMessage: 'Oops. That file is too large to be uploaded',
    passcodenotmatch: "Passcode don't match",
    correctpasscode: 'Enter correct Passcode',
    appOutdated: 'App ist veraltet',
    appOutdatedMessage: 'Bitte aktualisieren Sie die App, um fortzufahren.',
    athleteAccessDeniedTitle: 'Zugriff abgelehnt',
    athleteAccessDeniedDescription:
      'Sie haben keinen Zugriff, um diese ID-Nummer anzuzeigen. Wenn Sie Bedenken haben, wenden Sie sich bitte an Ihren Vorgesetzten oder senden Sie eine E-Mail an support@iracesafe.com',
    inAppTraining: 'In-App-Schulung',
    inAppTrainingTurnOn: 'Sie haben das In-App-Training aktiviert',
    inAppTrainingTurnOff: 'Sie haben das In-App-Training deaktiviert',
    close: 'Schließen',

    // --------------------------------------------------------
    // Form strings
    // --------------------------------------------------------
    viewAmrConsent: 'Ver formulário de consentimento',
    openRecordsCount: 'You have {0} Open Records to Close',
    upload: 'Upload',
    emailLabel: 'Email',
    idLabel: 'ENTER ID #',
    pulse: 'Impuls',
    bloodpressure: 'Blutdruck',
    breathing: 'Atmung',
    temperature: 'Temperatur',
    o2saturation: '02 Sättigung',
    sodium: 'Natrium',
    glucose: 'Glucose',
    note: 'Notiz',
    medication: 'Medikament',
    dose: 'Dosis',
    route: 'Route',
    otherAddnotes: 'Sonstiges (Notizen hinzufügen)',
    status: 'Status',
    timeEventResolved: 'Zeitereignis aufgelöst *',
    tapToEdit: '* Tippen Sie zum Bearbeiten',
    emailPlaceholder: 'e.g. jon@example.com',
    firstNameLabel: 'First name',
    athleteStatus: 'Sportler-Status',
    firstNamePlaceholder: 'e.g. Jon',
    successStatus: 'SUCCESS',
    lastNameLabel: 'Last name',
    notes: 'Notes',
    lastNamePlaceholder: 'e.g. Doe',
    userNameLabel: 'Username',
    userNamePlaceholder: 'e.g. jondoe',
    phoneLabel: 'Phone number',
    careProvider: 'Pflegeanbieter',
    reportedBy: 'Berichtet von',
    hospital: 'Krankenhaus',
    phonePlaceholder: '8122-09-1994',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    verificationCodeLabel: 'Verification code',
    recoveryCodeLabel:
      'Bitte geben Sie Ihren Passcode ein, der zum Entsperren der App verwendet wird.',
    reEnterRecoveryCodeLabel: 'Re-enter your Passcode',
    otpInputPlaceholder: '•',
    forgotPasswordLabel: 'Forgot Password?',
    setPasscode: 'Passcode festlegen',
    enterPasscode: 'Passwort eingeben',
    practicerace: 'Übungsrennen',
    pickanevent: 'Wählen Sie ein Ereignis aus',
    enterid: 'ID EINGEBEN',
    helpCenter: 'Hilfezentrum',
    referenceCenter: 'Referenzzentrum',
    cantLogIn: "Can't Log In",
    dontHaveAccount: "Don't have an Account?",
    register: 'REGISTER',
    send: 'SEND',
    forgotPassword: 'Forgot Password',
    back: 'Zurück',
    ok: 'Ok',
    takecareofanewproblem: 'Um ein neues Problem kümmern',
    enterANewProblem: 'Geben Sie ein neues Problem ein',
    selectAnExistingProblem: 'Wählen Sie ein bestehendes Problem aus',
    followup: 'Nachverfolgen',
    done: 'Erledigt',
    addnote: 'Add Note',
    renameTopicTitle: 'Rename Chat Topic',
    addfreeforminput: 'Fügen Sie hier Freiformeingaben hinzu',
    confirm: 'Bestätigen',
    duplicateIdsFound: 'Doppelte IDs gefunden',
    searchListInfo:
      'Mehrere Athleten haben dieselbe Such-ID, bitte wählen Sie die richtige aus',
    spotInjury: 'SPOT - INJURY',
    spotIllness: 'SPOT - ILLNESS',
    idsearchedhasnoathlete: 'ID gesucht hat keinen Athleten',
    youcanmakeNMR: 'Unten können Sie eine neue Krankenakte erstellen',
    heatProtocol: 'Hitze Protocol',
    save: 'Speichern',
    bodypartinjured: 'Körperteil verletzt',
    vitalsigns: 'Vitalfunktionen',
    symptoms: 'Symptome',
    physicalFindings: 'Körperliche Befunde',
    opinion: 'Meinung',
    treatment: 'Behandlung',
    dateOfBirth: 'Geburtsdatum',
    notifications: 'Benachrichtigungen',

    //-------------------------------------------------------
    //SPOT
    //--------------------------------------------------------
    providingCare: 'Behandeln',
    enterSpotorLab: 'Geben Sie SPOT- oder LAB-Daten ein',
    history: 'Geschichte',
    makeACall: 'Einen Anruf tätigen',
    takeaphoto: 'Mach ein Foto',
    uploadFile: 'Datei hochladen',
    resolveEvent: 'Ein Problem lösen',
    addInjury: 'Verletzung hinzufügen',
    addIllness: 'Krankheit hinzufügen',
    minor: 'Minor',
    delayed: 'Delayed',
    immediate: 'Immediate',
    otherpleaseadd: 'Sonstiges (Bitte hinzufügen)',
    cancel: 'Zurück',
    left: 'Left',
    right: 'Right',
    bilateral: 'Bilateral',

    // --------------------------------------------------------
    // Application strings
    // --------------------------------------------------------
    goHelpCenter: 'Go to Help Center',
    tryAgain: 'Try again',
    checkRegion: 'Check Region',
    youSelected: 'You Selected',
    adminDetected: 'Admin Detected',
    pleaseSelectData: 'Bitte wählen Sie die zu speichernden Daten aus.',
    selectAction:
      'Was willst du als nächstes tun? Wählen Sie eine Option oder gehen Sie zurück',
    isanewvisit: 'Is this a new visit?',
    adminDetectedSub:
      'Hello, I see you are a super admin, please, choose the server you want to connect to. Remember that in order to change servers you need to logout and login again.',
    usa: 'USA',
    canada: 'Canada',
    germany: 'German',
    logout: 'Ausloggen',
    language: 'Sprache',
    contacts: 'Kontakte',
    yourResolvedRecords: 'Ihre aufgelösten Aufzeichnungen',
    yourOfflineRecords: 'Ihre Offline-Aufzeichnungen',
    yourActiveRecords: 'Ihre offenen Aufzeichnungen',
    checkedInRecords: 'Ihre eingecheckten Aufzeichnungen',
    pickEvent: 'Wählen Sie ein Ereignis aus',
    deleteAccount: 'Konto löschen',
    home: 'Heim',
    yes: 'Yes',
    no: 'No',
    eventAction: 'eventAction',
    eventDisposition: 'eventDisposition',
    minorAssisitance: 'minorAssisitance',
    checkin: 'checkin',
    checkout: 'checkout',
    forgotPasswordSub:
      'Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen per E-Mail Anweisungen für den Zugriff auf Ihr Konto',
    biometricsPopupTitleAndroid: 'Confirm your biometrics to continue',
    biometricsPopupTitleIOS: 'Confirm your biometrics to continue',
    biometricsAuthenticationFailed: 'Biometrics authentication failed',
    appleSignInButtonTitle: 'Sign in with Apple',
    facebookSignInButtonTitle: 'Continue with Facebook',
    loginButtonTitle: 'Log in',
    signUpButtonTitle: 'Sign up',
    signUpModalTitle: 'Sign up',
    signUpModalSubtitle: 'Get started in a few simple steps!',
    facebookSignUpButtonTitle: 'Sign up with Facebook',
    googleSignUpButtonTitle: 'Sign up with Google',
    emailSignUpButtonTitle: 'Get started now',
    appleSignUpButtonTitle: 'Sign up with Apple',
    loginTitle: 'Welcome back!',
    loginSubtitle: 'Sign in with your email and password to continue.',
    signInButtonTitle: 'SIGN IN',
    enterManualRunnerInfo: 'Geben Sie manuelle Läuferinformationen ein',
    createMedicalRecord: 'Erstellen Sie eine Krankenakte',
    confirmInfo: 'Informationen bestätigen',
    searchAthleteMed: 'Search Athlete Medical Record',
    recordMinorAssistance: 'Record Minor Assistance',
    searchAthleteMedTrans: 'Durchsuchen Sie die Krankenakte des Athleten',
    recordMinorAssistanceTrans: 'Notieren Sie kleinere Hilfeleistungen',
    checkIn: 'Check In',
    checkOut: 'Check Out',
    altSignInTitle: 'or sign in with',
    signInTermsText: 'By continuing, you confirm that you agree with our',
    termsLinkTitle: 'terms and conditions',
    registerPretitle: 'STEP {0} OF {1}',
    registerTitle: 'Create an account.',
    signUpNextButtonTitle: 'Next',
    signUpFinishButtonTitle: 'Finish',
    authHelpButtonTitle: 'Help',
    profileSelectTitle: 'Choose your profile type.',
    profileSelectSubtitle:
      'Select your profile type to proceed to the next step.',
    verifyTitle: 'Verify your email',
    verifySubtitle: 'We sent your verification code to {0}.',
    resendCodeText: "Didn't get the code?",
    resendCodeTimerText: 'Resend in ',
    resendCodeButtonText: 'Tap to resend',
    verifyButtonTitle: 'Verify',
    servicesModalDefaultTitle: 'What services do you offer?',
    servicesModalButtonTitle: 'Select {0} {1}',
    onboardingCompleteTitle: 'Great job!',
    incorrectEmailPassword: 'You have entered an incorrect email or password.',
    incorrectEmail: 'Incorrect Email or Email not registered',
    resetInstruction: 'Reset Instruction Sent',
    resetInstructionBody:
      'Kindly check email address and follow the instructions to reset password',
    onboardingCompleteAltButtonTitle: 'or continue to your dashboard',
    resetEmailTitle: 'Forgot password?',
    resetEmailSubtitle:
      'Enter the email you registered with and we’ll send you a recovery code.',
    resetCodeTitle: 'Verify your account.',
    resetCodeSubtitle: 'Please enter the 4 digit recovery code we sent to {0}.',
    resetPasswordTitle: 'Set a new password.',
    resetPasswordSubtitle:
      'Use a super memorable combination of letters, numbers and special characters.',
    resetContinueButton: 'Continue',
    resetFinishButton: 'Finish',
    networkIssue: 'Network Issue',
    connectToInternetToUploadData:
      'Stellen Sie eine Verbindung zum Internet her, um Daten hochzuladen',
    heyWait: 'Hey warte!',
    whatDoYouWantToDo: 'Was möchten Sie tun?',
    scanQROrBarCode: 'QR oder Barcode scannen',
    problemList: 'Problemliste',
    closedRecords: 'Geschlossene Aufzeichnungen (zum Anzeigen auswählen)',
    allergies: 'Allergien',
    currentMedications: 'Derzeitige Medikamente',
    illnessConditions: 'Krankheitsbedingungen',
    surgeries: 'Operationen',
    musculoskeletalConditions: 'Erkrankungen des Bewegungsapparates',
    athleteFiles: 'Athletendateien',

    enterMedicationsGiven:
      'Bitte beschreiben Sie die unten aufgeführten Medikamente',
    selectOneOption: 'Wählen Sie eine Option',
    proceedToDelete: 'Fahren Sie mit dem Löschen des Kontos fort !',
    pickaLanguage: 'Wählen Sie eine Sprache',
    resolveProblem: 'Ein Problem lösen',
    pickHospital: 'Wählen Sie Krankenhaus',
    greatJob: 'Gut gemacht!',
    oops: 'Hoppla!',
    successfullyResolvedProblem: 'Sie haben das Problem erfolgreich gelöst',
    phoneCurrentLocation: 'Der aktuelle Standort dieses Telefons',
    notNecessarilyLocationAthlete:
      '(Nicht unbedingt der Standort des Sportlers)',
    areYouSure: 'Bist du dir sicher?',
    aboutToDowngradeStatus:
      'Sie sind im Begriff, den Status herabzustufen. Bitte bestätigen Sie, ob Sie fortfahren möchten.',
    startSpecialProtocol: 'Spezielles Protokoll starten',
    openGallery: 'Galerie öffnen',
    camera: 'Kamera',
    selectFile: 'Datei aussuchen',
    photoUploadedSuccess: 'Foto erfolgreich hochgeladen',
    workingOfflineMode: 'Arbeiten im Offline-Modus',
    alternativeFormsCommunication:
      'Bitte nutzen Sie alternative Kommunikationsformen, bis sich die Netzabdeckung verbessert',
    selectProblem: 'Wählen Sie Problem',
    closeEventWithoutOpinion:
      'Sie schließen eine Veranstaltung ohne Stellungnahme ab',
    existingDisposition: 'Exisiting Disposition',
    sureToCloseEventWithoutOpinion:
      'Sind Sie sicher, dass Sie diese Veranstaltung schließen möchten, ohne eine Meinung abzugeben??',

    // --------------------------------------------------------
    // In App Training
    // --------------------------------------------------------
    iatModalTitle: 'In-App-Schulung',
    iatModalSubtitle:
      'Wählen Sie aus, wann In-App-Schulungstipps angezeigt werden sollen',
    iatShowNow: 'Jetzt einschalten und Tipps anzeigen',
    iatShowLater: 'Einschalten und Tipps später anzeigen',
    iatShowNever: 'Training ausschalten',

    iatAddPerson: 'Person hinzufügen, falls erforderlich',
    iatShowsEvent: 'Zeigt Veranstaltung',
    iatPickAnOption: 'Option auswählen',
    iatSelectSearchMethod: 'Suchmethode auswählen',
    iatOpenToReadRecord: 'Datensatz anzeigen',
    iatOpenCameraOrUploadFile: 'Kamera öffnen oder Datei hochladen',
    iatOpenToDocumentCare: 'Zur Dokumentenpflege öffnen',
    iatStatus: 'Zeigt den Status an bzw. ändert ihn',
    iatPersonalInformation: 'Persönliche Informationen anzeigen',
    iatAddNewProblem: 'Neues Problem hinzufügen',
    iatTouchToMakeACall: 'Berühren, um einen Anruf zu tätigen',
    iatSelectAProblem:
      'Wählen Sie ein Problem zur Nachverfolgung aus. Berühren Sie Augapfel, um die Notiz anzuzeigen',
  },
});

export function setStrings(to: Record<string, Record<string, string>>) {
  strings.setContent({...(strings as any).getContent(), ...to});
}

export function setRaceLanguage(language: string) {
  strings.setLanguage(language);
}

export default strings;
